name: master
on:
  push:
    branches:    
      - master

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - uses: actions/checkout@v1
    - run: make test
      env:
        GO_TEST_ARGS: "-coverprofile=coverage.txt -covermode=atomic"
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt

  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - uses: actions/checkout@v1
    - run: |
        echo $GCLOUD_SERVICE_KEY > /tmp/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json
        make test_integration
      env:
        GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}